export const produitsBoutique = [
  {
    id: "tshirt-homme-or",
    type: "T-shirt",
    categorie: "T-shirt Homme",
    modele: "T-shirts homme Or",
    sexe: "homme",
    couleur: "Or",
    prix: 20,
    imageDevant: "/tshirt-homme-or-devant.png",
    imageDos: "/tshirt-homme-or-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
  },
  {
    id: "tshirt-homme-sable",
    type: "T-shirt",
    categorie: "T-shirt Homme",
    modele: "T-shirts homme Sable",
    sexe: "homme",
    couleur: "Sable",
    prix: 20,
    imageDevant: "/tshirt-homme-sable-devant.png",
    imageDos: "/tshirt-homme-sable-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
  },
  {
    id: "tshirt-femme-blanc",
    type: "T-shirt",
    categorie: "T-shirt Femme",
    modele: "T-shirts femme Blanc",
    sexe: "femme",
    couleur: "Blanc",
    prix: 20,
    imageDevant: "/tshirt-femme-blanc-devant.png",
    imageDos: "/tshirt-femme-blanc-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "tshirt-femme-rose",
    type: "T-shirt",
    categorie: "T-shirt Femme",
    modele: "T-shirts femme Rose",
    sexe: "femme",
    couleur: "Rose",
    prix: 20,
    imageDevant: "/tshirt-femme-rose-devant.png",
    imageDos: "/tshirt-femme-rose-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "camisole-homme-blanc",
    type: "Camisole",
    categorie: "Camisole Homme",
    modele: "Camisoles homme Blanc",
    sexe: "homme",
    couleur: "Blanc",
    prix: 20,
    imageDevant: "/camisole-homme-blanc-devant.png",
    imageDos: "/camisole-homme-blanc-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
  },
  {
    id: "camisole-homme-marine",
    type: "Camisole",
    categorie: "Camisole Homme",
    modele: "Camisoles homme Marine",
    sexe: "homme",
    couleur: "Marine",
    prix: 20,
    imageDevant: "/camisole-homme-marin-devant.png",
    imageDos: "/camisole-homme-marin-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
  },
  {
    id: "camisole-femme-bleu",
    type: "Camisole",
    categorie: "Camisole Femme",
    modele: "Camisoles femme Bleu",
    sexe: "femme",
    couleur: "Bleu",
    prix: 20,
    imageDevant: "/camisole-femme-bleue-devant.png",
    imageDos: "/camisole-femme-bleue-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "camisole-femme-rose",
    type: "Camisole",
    categorie: "Camisole Femme",
    modele: "Camisoles femme Rose",
    sexe: "femme",
    couleur: "Rose",
    prix: 20,
    imageDevant: "/camisole-femme-rose-devant.png",
    imageDos: "/camisole-femme-rose-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL"],
  },
  {
    id: "hoodie-unisex-marine",
    type: "Hoodie",
    categorie: "Hoodie Unisex",
    modele: "Hoodies unisex Marine",
    sexe: "unisex",
    couleur: "Marine",
    prix: 40,
    imageDevant: "/hoodie-unisex-marin-devant.png",
    imageDos: "/hoodie-unisex-marin-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
  },
  {
    id: "hoodie-unisex-or",
    type: "Hoodie",
    categorie: "Hoodie Unisex",
    modele: "Hoodies unisex Or",
    sexe: "unisex",
    couleur: "Or",
    prix: 40,
    imageDevant: "/hoodie-unisex-or-devant.png",
    imageDos: "/hoodie-unisex-or-dos.png",
    grandeurs: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL"],
  },
];
